import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRef, useState } from "react";

export default function Home() {
  const blockOuterRef = useRef<HTMLDivElement>(null);
  const blockInnerRef = useRef<HTMLDivElement>(null);
  const [rotationAngle, setRotationAngle] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [blockColor, setBlockColor] = useState("pink");

  const handleBlockDoubleClick = () => {
    setIsFlipped(!isFlipped);
    setBlockColor((prevColor) => (prevColor === "pink" ? "blue" : "pink"));
    // 現在の角度に180度を加える
    setRotationAngle((prevAngle) => prevAngle + 180);
    if (!blockOuterRef.current) return;
    blockOuterRef.current.style.boxShadow = "0px 4px 4px rgba(0, 0, 0, 0.2)";
  };

  const handleTransitionEnd = () => {
    if (!blockOuterRef.current) return;
    blockOuterRef.current.style.boxShadow = isFlipped
      ? "-4px 4px 3px rgba(0, 0, 0, 0.5)"
      : "4px 4px 3px rgba(0, 0, 0, 0.5)";
  };

  // 回転スタイルの作成
  const rotationStyle = {
    transform: `rotateY(${rotationAngle}deg)`,
    transition: "transform 0.2s ease",
    transformOrigin: "center",
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center min-h-screen py-2 bg-gray-200">
        <h1 className="text-4xl font-bold text-gray-700">すうず　ぶろっく</h1>

        <div
          ref={blockOuterRef}
          className={styles.suuzuBlockOuter}
          onDoubleClick={handleBlockDoubleClick}
          onTransitionEnd={handleTransitionEnd}
          style={{ ...rotationStyle }}
        >
          <div ref={blockInnerRef} className={styles.suuzuBlockInner} style={{ backgroundColor: blockColor }}></div>
        </div>
      </main>
    </>
  );
}
